/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hms.view.panels;

import hms.controller.BillingController;
import hms.controller.DashboardObserver;
import hms.controller.ReservationController;
import hms.controller.RoomController;
import hms.exception.DatabaseException;
import hms.model.Reservation;
import hms.model.Room;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vickrant
 */
public class DashboardPanel extends javax.swing.JPanel implements DashboardObserver {

    /**
     * Creates new form DashPanel
     */
    private final ReservationController reservationController = new ReservationController();
    private final RoomController roomController = new RoomController();
    private final BillingController billingController = new BillingController();

    public DashboardPanel() {
        initComponents();
        applyThemeBorders();
        loadDashboardData();
    }

    private void applyThemeBorders() {
        java.awt.Color borderColor = UIManager.getColor("Component.borderColor");
        if (borderColor == null) borderColor = new java.awt.Color(76, 76, 76);
        stat_card_1.setBorder(new javax.swing.border.LineBorder(borderColor, 1, true));
        stat_card_2.setBorder(new javax.swing.border.LineBorder(borderColor, 1, true));
        stat_card_3.setBorder(new javax.swing.border.LineBorder(borderColor, 1, true));
        stat_card_4.setBorder(new javax.swing.border.LineBorder(borderColor, 1, true));
        revenue_summary_chart.setBorder(new javax.swing.border.LineBorder(borderColor, 1, true));
        recent_checkins.setBorder(new javax.swing.border.LineBorder(borderColor, 1, true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardGroup = new javax.swing.JPanel();
        stat_card_1 = new hms.theme.RoundedPanel(16);
        jPanel3 = new hms.theme.RoundedPanel(10);
        jLabel1 = new javax.swing.JLabel();
        stat_card_val_1 = new javax.swing.JLabel();
        stat_card_2 = new hms.theme.RoundedPanel(16);
        jPanel4 = new hms.theme.RoundedPanel(10);
        jLabel2 = new javax.swing.JLabel();
        stat_card_val_2 = new javax.swing.JLabel();
        stat_card_3 = new hms.theme.RoundedPanel(16);
        jPanel6 = new hms.theme.RoundedPanel(10);
        jLabel3 = new javax.swing.JLabel();
        stat_card_val_3 = new javax.swing.JLabel();
        stat_card_4 = new hms.theme.RoundedPanel(16);
        jPanel11 = new hms.theme.RoundedPanel(10);
        jLabel4 = new javax.swing.JLabel();
        stat_card_val_4 = new javax.swing.JLabel();
        revenue_summary_chart = new hms.theme.RoundedPanel(16);
        jLabel9 = new javax.swing.JLabel();
        revenue_weekly_btn = new javax.swing.JLabel();
        revenue_daily_btn = new javax.swing.JLabel();
        recent_checkins = new hms.theme.RoundedPanel(20);
        jLabel23 = new javax.swing.JLabel();
        viewAllReservationsBtn = new javax.swing.JLabel();
        checkInsTable = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();

        stat_card_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));
        stat_card_1.setPreferredSize(new java.awt.Dimension(190, 2));

        jPanel3.setBackground(new java.awt.Color(169, 202, 238));
        jPanel3.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("TOTAL OCCUPANCY");

        stat_card_val_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stat_card_val_1.setText("84.56%");

        javax.swing.GroupLayout stat_card_1Layout = new javax.swing.GroupLayout(stat_card_1);
        stat_card_1.setLayout(stat_card_1Layout);
        stat_card_1Layout.setHorizontalGroup(
            stat_card_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stat_card_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(stat_card_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(stat_card_val_1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stat_card_1Layout.setVerticalGroup(
            stat_card_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stat_card_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stat_card_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stat_card_1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stat_card_val_1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        stat_card_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));
        stat_card_2.setPreferredSize(new java.awt.Dimension(190, 2));

        jPanel4.setBackground(new java.awt.Color(46, 204, 113));
        jPanel4.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setText("DAILY REVENUE (LKR)");

        stat_card_val_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stat_card_val_2.setText("LKR 12,450.00");

        javax.swing.GroupLayout stat_card_2Layout = new javax.swing.GroupLayout(stat_card_2);
        stat_card_2.setLayout(stat_card_2Layout);
        stat_card_2Layout.setHorizontalGroup(
            stat_card_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stat_card_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(stat_card_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(stat_card_val_2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stat_card_2Layout.setVerticalGroup(
            stat_card_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stat_card_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stat_card_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stat_card_2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stat_card_val_2))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        stat_card_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));
        stat_card_3.setPreferredSize(new java.awt.Dimension(190, 2));

        jPanel6.setBackground(new java.awt.Color(147, 0, 10));
        jPanel6.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setText("PENDING CHECK-INS");

        stat_card_val_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stat_card_val_3.setText("12");

        javax.swing.GroupLayout stat_card_3Layout = new javax.swing.GroupLayout(stat_card_3);
        stat_card_3.setLayout(stat_card_3Layout);
        stat_card_3Layout.setHorizontalGroup(
            stat_card_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stat_card_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(stat_card_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(stat_card_val_3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stat_card_3Layout.setVerticalGroup(
            stat_card_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stat_card_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stat_card_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stat_card_3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stat_card_val_3))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        stat_card_4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));
        stat_card_4.setPreferredSize(new java.awt.Dimension(190, 2));

        jPanel11.setBackground(new java.awt.Color(152, 184, 220));
        jPanel11.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setText("HOUSEKEEPING ALERTS");

        stat_card_val_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stat_card_val_4.setText("04");

        javax.swing.GroupLayout stat_card_4Layout = new javax.swing.GroupLayout(stat_card_4);
        stat_card_4.setLayout(stat_card_4Layout);
        stat_card_4Layout.setHorizontalGroup(
            stat_card_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stat_card_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(stat_card_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(stat_card_val_4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stat_card_4Layout.setVerticalGroup(
            stat_card_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stat_card_4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stat_card_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stat_card_4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stat_card_val_4))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        revenue_summary_chart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Revenue Summary (Last 7 days)");

        revenue_weekly_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        revenue_weekly_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        revenue_weekly_btn.setText("Weekly");
        revenue_weekly_btn.setToolTipText("");

        revenue_daily_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        revenue_daily_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        revenue_daily_btn.setText("Daily");

        javax.swing.GroupLayout revenue_summary_chartLayout = new javax.swing.GroupLayout(revenue_summary_chart);
        revenue_summary_chart.setLayout(revenue_summary_chartLayout);
        revenue_summary_chartLayout.setHorizontalGroup(
            revenue_summary_chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenue_summary_chartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(448, 448, 448)
                .addComponent(revenue_daily_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(revenue_weekly_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        revenue_summary_chartLayout.setVerticalGroup(
            revenue_summary_chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenue_summary_chartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(revenue_summary_chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(revenue_weekly_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revenue_daily_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        recent_checkins.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Recent Check-ins");

        viewAllReservationsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewAllReservationsBtn.setText("View all reservations");

        checkInsTable.setBorder(null);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Alexander", "402 (Deluxe)", "Oct 24 - 28", "Res-845569", "ACTIVE",  new Double(0.0)},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Guest Name", "Room", "Duration", "Booking ID", "Status", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        checkInsTable.setViewportView(jTable6);

        javax.swing.GroupLayout recent_checkinsLayout = new javax.swing.GroupLayout(recent_checkins);
        recent_checkins.setLayout(recent_checkinsLayout);
        recent_checkinsLayout.setHorizontalGroup(
            recent_checkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recent_checkinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recent_checkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkInsTable)
                    .addGroup(recent_checkinsLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewAllReservationsBtn)))
                .addContainerGap())
        );
        recent_checkinsLayout.setVerticalGroup(
            recent_checkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recent_checkinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recent_checkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(viewAllReservationsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkInsTable, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dashboardGroupLayout = new javax.swing.GroupLayout(dashboardGroup);
        dashboardGroup.setLayout(dashboardGroupLayout);
        dashboardGroupLayout.setHorizontalGroup(
            dashboardGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardGroupLayout.createSequentialGroup()
                        .addComponent(stat_card_1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(stat_card_2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(stat_card_3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(stat_card_4, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                    .addComponent(revenue_summary_chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recent_checkins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashboardGroupLayout.setVerticalGroup(
            dashboardGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stat_card_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stat_card_2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stat_card_3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stat_card_4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(revenue_summary_chart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recent_checkins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dashboardGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadDashboardData() {
        try { loadOccupancy(); } catch (Exception e) { /* degrade gracefully */ }
        try { loadDailyRevenue(); } catch (Exception e) { /* degrade gracefully */ }
        try { loadPendingCheckIns(); } catch (Exception e) { /* degrade gracefully */ }
        try { loadRecentCheckIns(); } catch (Exception e) { /* degrade gracefully */ }
        try { loadHousekeepingAlerts(); } catch (Exception e) { /* degrade gracefully */ }
    }

    private void loadOccupancy() {
        try {
            List<Room> allRooms = roomController.getAllRooms();
            long total = allRooms.size();
            long occupied = allRooms.stream()
                .filter(r -> !"available".equalsIgnoreCase(r.getStatus()))
                .count();
            double rate = total > 0 ? (occupied * 100.0 / total) : 0.0;
            stat_card_val_1.setText(String.format("%.2f%%", rate));
        } catch (DatabaseException e) {
            stat_card_val_1.setText("N/A");
        }
    }

    private void loadDailyRevenue() {
        try {
            LocalDate today = LocalDate.now();
            double revenue = billingController.getRevenueByDateRange(today, today);
            stat_card_val_2.setText("LKR " + String.format("%,.2f", revenue));
        } catch (DatabaseException e) {
            stat_card_val_2.setText("N/A");
        }
    }

    private void loadPendingCheckIns() {
        try {
            List<Reservation> all = reservationController.getAllReservations();
            long pending = all.stream()
                .filter(r -> "confirmed".equalsIgnoreCase(r.getStatus()))
                .count();
            stat_card_val_3.setText(String.valueOf(pending));
        } catch (DatabaseException e) {
            stat_card_val_3.setText("N/A");
        }
    }

    private void loadRecentCheckIns() {
        try {
            List<Reservation> all = reservationController.getAllReservations();
            List<Reservation> recent = all.stream()
                .filter(r -> "checked_in".equalsIgnoreCase(r.getStatus())
                    || "confirmed".equalsIgnoreCase(r.getStatus()))
                .sorted((a, b) -> b.getBookingDate().compareTo(a.getBookingDate()))
                .limit(5)
                .toList();

            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Guest Name", "Room", "Duration", "Booking ID", "Status", "Balance"}, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int col) { return false; }
            };

            for (Reservation r : recent) {
                String guestName = r.getGuest().getFirstName() + " " + r.getGuest().getLastName();
                String room = r.getRoom().getRoomNumber() + " (" + r.getRoom().getRoomType() + ")";
                String duration = r.getCheckInDate() + " - " + r.getCheckOutDate();
                model.addRow(new Object[]{
                    guestName, room, duration, r.getDisplayId(),
                    r.getStatus().toUpperCase(), r.getTotalAmount()
                });
            }

            jTable6.setModel(model);
        } catch (DatabaseException e) {
            // table stays empty
        }
    }

    private void loadHousekeepingAlerts() {
        try {
            List<Room> allRooms = roomController.getAllRooms();
            long maintenance = allRooms.stream()
                .filter(r -> "maintenance".equalsIgnoreCase(r.getStatus()))
                .count();
            stat_card_val_4.setText(String.valueOf(maintenance));
        } catch (DatabaseException e) {
            stat_card_val_4.setText("N/A");
        }
    }

    @Override
    public void onReservationCreated(Reservation r) {
        loadDashboardData();
    }

    @Override
    public void onCheckIn(Reservation r) {
        loadDashboardData();
    }

    @Override
    public void onCheckOut(Reservation r) {
        loadDashboardData();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane checkInsTable;
    private javax.swing.JPanel dashboardGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTable jTable6;
    private javax.swing.JPanel recent_checkins;
    private javax.swing.JLabel revenue_daily_btn;
    private javax.swing.JPanel revenue_summary_chart;
    private javax.swing.JLabel revenue_weekly_btn;
    private javax.swing.JPanel stat_card_1;
    private javax.swing.JPanel stat_card_2;
    private javax.swing.JPanel stat_card_3;
    private javax.swing.JPanel stat_card_4;
    private javax.swing.JLabel stat_card_val_1;
    private javax.swing.JLabel stat_card_val_2;
    private javax.swing.JLabel stat_card_val_3;
    private javax.swing.JLabel stat_card_val_4;
    private javax.swing.JLabel viewAllReservationsBtn;
    // End of variables declaration//GEN-END:variables
}
