/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hms.view.panels;

/**
 *
 * @author vickrant
 */
public class GuestManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form GuestManagementPanel2
     */
    public GuestManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guest_management_panel_grp = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        add_guest_btn = new javax.swing.JButton();
        guest_seperator_1 = new javax.swing.JSeparator();
        search_field = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        guest_table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pagination_value = new javax.swing.JLabel();

        heading.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        heading.setText("Guest Management");

        description.setText("Manage guest records, identities, and visit history");

        add_guest_btn.setText("Add Guest");

        search_field.setText("Search by name, email or phone...");

        search_btn.setText("Search");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "FIRST NAME", "LAST NAME", "EMAIL", "PHONE", "ID TYPE", "ID NUMBER", "DOB", "CREATED AT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        guest_table.setViewportView(jTable1);

        pagination_value.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pagination_value.setText("Page 1 of 5");

        javax.swing.GroupLayout guest_management_panel_grpLayout = new javax.swing.GroupLayout(guest_management_panel_grp);
        guest_management_panel_grp.setLayout(guest_management_panel_grpLayout);
        guest_management_panel_grpLayout.setHorizontalGroup(
            guest_management_panel_grpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guest_management_panel_grpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guest_management_panel_grpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guest_seperator_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guest_management_panel_grpLayout.createSequentialGroup()
                        .addGroup(guest_management_panel_grpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heading)
                            .addComponent(description))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_guest_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(guest_management_panel_grpLayout.createSequentialGroup()
                        .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(guest_table, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guest_management_panel_grpLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pagination_value)))
                .addContainerGap())
        );
        guest_management_panel_grpLayout.setVerticalGroup(
            guest_management_panel_grpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guest_management_panel_grpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guest_management_panel_grpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_guest_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(guest_management_panel_grpLayout.createSequentialGroup()
                        .addComponent(heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(description)))
                .addGap(18, 18, 18)
                .addComponent(guest_seperator_1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(guest_management_panel_grpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(guest_table, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pagination_value)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guest_management_panel_grp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guest_management_panel_grp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_guest_btn;
    private javax.swing.JLabel description;
    private javax.swing.JPanel guest_management_panel_grp;
    private javax.swing.JSeparator guest_seperator_1;
    private javax.swing.JScrollPane guest_table;
    private javax.swing.JLabel heading;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel pagination_value;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_field;
    // End of variables declaration//GEN-END:variables
}
