/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hms.view.panels;

import hms.controller.GuestController;
import hms.exception.DatabaseException;
import hms.model.Guest;
import java.awt.Frame;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import hms.view.dialogs.AddGuestDialog;
import hms.util.IconUtil;

/**
 *
 * @author vickrant
 */
public class GuestManagementPanel extends javax.swing.JPanel {

    private final GuestController guestController = new GuestController();
    private List<Guest> filteredGuests;
    private int currentPage = 0;
    private static final int PAGE_SIZE = 10;

    /**
     * Creates new form GuestManagementPanel2
     */
    public GuestManagementPanel() {
        initComponents();
        setupTable();
        setupPaginationListeners();
        setupIcons();
        loadGuests();
    }

    private void loadGuests() {
        try {
            filteredGuests = guestController.getAllGuests();
            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Failed to load guests: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void applyPagination() {
        int total = filteredGuests.size();
        int totalPages = Math.max(1, (int) Math.ceil((double) total / PAGE_SIZE));
        if (currentPage >= totalPages) currentPage = totalPages - 1;
        if (currentPage < 0) currentPage = 0;

        int from = currentPage * PAGE_SIZE;
        int to = Math.min(from + PAGE_SIZE, total);
        List<Guest> page = from < total ? filteredGuests.subList(from, to) : List.of();

        String[][] data = new String[page.size()][10];
        for (int i = 0; i < page.size(); i++) {
            Guest g = page.get(i);
            data[i][0] = String.valueOf(g.getGuestId());
            data[i][1] = g.getFirstName();
            data[i][2] = g.getLastName();
            data[i][3] = g.getEmail();
            data[i][4] = g.getPhone();
            data[i][5] = g.getIdProofType() != null ? g.getIdProofType() : "";
            data[i][6] = g.getIdProofNumber() != null ? g.getIdProofNumber() : "";
            data[i][7] = g.getDateOfBirth() != null ? g.getDateOfBirth().toString() : "";
            data[i][8] = g.getCreatedAt() != null ? g.getCreatedAt().toLocalDate().toString() : "";
            data[i][9] = "Active";
        }

        guestManagementTable.setModel(new javax.swing.table.DefaultTableModel(data, new String[]{
            "#", "FIRST NAME", "LAST NAME", "EMAIL", "PHONE", "ID TYPE", "ID NUMBER", "DOB", "CREATED AT", "STATUS"
        }) {
            boolean[] canEdit = {false, false, false, false, false, false, false, false, false, false};
            @Override public boolean isCellEditable(int row, int col) { return canEdit[col]; }
        });

        pageNumber.setText("Page " + (currentPage + 1) + " of " + totalPages);
        totalRecords.setText("Records: " + total);
    }

    private Guest getSelectedGuest() {
        int viewRow = guestManagementTable.getSelectedRow();
        if (viewRow == -1 || filteredGuests == null) return null;
        return filteredGuests.get(guestManagementTable.convertRowIndexToModel(viewRow));
    }

    private void setupTable() {
        guestManagementTable.getSelectionModel().addListSelectionListener(e -> {
            boolean hasSelection = guestManagementTable.getSelectedRow() != -1;
            editGuestBtn.setEnabled(hasSelection);
            deleteGuestBtn.setEnabled(hasSelection);
            viewHistoryBtn.setEnabled(hasSelection);
        });
        editGuestBtn.setEnabled(false);
        deleteGuestBtn.setEnabled(false);
        viewHistoryBtn.setEnabled(false);
    }

    private void setupPaginationListeners() {
        guestPaginationLeft.addActionListener(e -> {
            if (currentPage > 0) { currentPage--; applyPagination(); }
        });
        guestPaginationRight.addActionListener(e -> {
            int totalPages = Math.max(1, (int) Math.ceil((double) filteredGuests.size() / PAGE_SIZE));
            if (currentPage < totalPages - 1) { currentPage++; applyPagination(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guestManagementPanelGroup = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        addGuestBtn = new javax.swing.JButton();
        guest_seperator_1 = new javax.swing.JSeparator();
        searchBox = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        guest_table = new javax.swing.JScrollPane();
        guestManagementTable = new javax.swing.JTable();
        bottomBar = new javax.swing.JPanel();
        editGuestBtn = new javax.swing.JButton();
        deleteGuestBtn = new javax.swing.JButton();
        viewHistoryBtn = new javax.swing.JButton();
        guestPaginationLeft = new javax.swing.JButton();
        guestPaginationRight = new javax.swing.JButton();
        pageNumber = new javax.swing.JLabel();
        totalRecords = new javax.swing.JLabel();

        heading.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        heading.setText("Guest Management");

        description.setText("Manage guest records, identities, and visit history");

        addGuestBtn.setText("Add Guest");
        addGuestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGuestBtnActionPerformed(evt);
            }
        });

        searchBox.setToolTipText("Search by name, email or phone...");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        guestManagementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "FIRST NAME", "LAST NAME", "EMAIL", "PHONE", "ID TYPE", "ID NUMBER", "DOB", "CREATED AT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        guest_table.setViewportView(guestManagementTable);

        bottomBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        editGuestBtn.setText("Edit");
        editGuestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGuestBtnActionPerformed(evt);
            }
        });

        deleteGuestBtn.setText("Delete");
        deleteGuestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGuestBtnActionPerformed(evt);
            }
        });

        viewHistoryBtn.setText("View History");
        viewHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryBtnActionPerformed(evt);
            }
        });

        guestPaginationLeft.setText("<");

        guestPaginationRight.setText(">");

        pageNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pageNumber.setText("Page 1 of 5");

        totalRecords.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalRecords.setText("Records: 10");

        javax.swing.GroupLayout bottomBarLayout = new javax.swing.GroupLayout(bottomBar);
        bottomBar.setLayout(bottomBarLayout);
        bottomBarLayout.setHorizontalGroup(
            bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editGuestBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteGuestBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewHistoryBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalRecords)
                .addGap(18, 18, 18)
                .addComponent(guestPaginationLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestPaginationRight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pageNumber)
                .addContainerGap())
        );
        bottomBarLayout.setVerticalGroup(
            bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editGuestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteGuestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pageNumber)
                        .addComponent(guestPaginationLeft)
                        .addComponent(guestPaginationRight)
                        .addComponent(totalRecords)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout guestManagementPanelGroupLayout = new javax.swing.GroupLayout(guestManagementPanelGroup);
        guestManagementPanelGroup.setLayout(guestManagementPanelGroupLayout);
        guestManagementPanelGroupLayout.setHorizontalGroup(
            guestManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guestManagementPanelGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guestManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bottomBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guest_seperator_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestManagementPanelGroupLayout.createSequentialGroup()
                        .addGroup(guestManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heading)
                            .addComponent(description))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addGuestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(guest_table, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(guestManagementPanelGroupLayout.createSequentialGroup()
                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        guestManagementPanelGroupLayout.setVerticalGroup(
            guestManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guestManagementPanelGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guestManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addGuestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(guestManagementPanelGroupLayout.createSequentialGroup()
                        .addComponent(heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(description)))
                .addGap(18, 18, 18)
                .addComponent(guest_seperator_1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(guestManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(guest_table, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottomBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guestManagementPanelGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guestManagementPanelGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editGuestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGuestBtnActionPerformed
        Guest selected = getSelectedGuest();
        if (selected == null) return;
        AddGuestDialog d = new AddGuestDialog((Frame) SwingUtilities.getWindowAncestor(this), true, selected);
        d.setTitle("Edit Guest: " + selected.getFirstName() + " " + selected.getLastName());
        d.setVisible(true);
        loadGuests();
    }//GEN-LAST:event_editGuestBtnActionPerformed

    private void deleteGuestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGuestBtnActionPerformed
        Guest selected = getSelectedGuest();
        if (selected == null) return;
        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete guest " + selected.getFirstName() + " " + selected.getLastName() + "?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                guestController.deleteGuest(selected.getGuestId());
                loadGuests();
            } catch (DatabaseException e) {
                JOptionPane.showMessageDialog(this, "Failed to delete guest: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteGuestBtnActionPerformed

    private void viewHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryBtnActionPerformed
        Guest selected = getSelectedGuest();
        if (selected == null) return;
        JOptionPane.showMessageDialog(this, "Guest history for " + selected.getFirstName()
            + " " + selected.getLastName() + " will be shown here.");
    }//GEN-LAST:event_viewHistoryBtnActionPerformed

    private void addGuestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGuestBtnActionPerformed
        AddGuestDialog d = new AddGuestDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setVisible(true);
        loadGuests();
    }//GEN-LAST:event_addGuestBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String keyword = searchBox.getText().trim();
        try {
            filteredGuests = keyword.isEmpty()
                ? guestController.getAllGuests()
                : guestController.searchGuests(keyword);
            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Search failed: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed


    private void setupIcons() {
        addGuestBtn.setIcon(IconUtil.getAddIcon());
        editGuestBtn.setIcon(IconUtil.getEditIcon());
        deleteGuestBtn.setIcon(IconUtil.getDeleteIcon());
        viewHistoryBtn.setIcon(IconUtil.getEyeIcon());
        searchBtn.setIcon(IconUtil.getSearchIcon());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGuestBtn;
    private javax.swing.JPanel bottomBar;
    private javax.swing.JButton deleteGuestBtn;
    private javax.swing.JLabel description;
    private javax.swing.JButton editGuestBtn;
    private javax.swing.JPanel guestManagementPanelGroup;
    private javax.swing.JTable guestManagementTable;
    private javax.swing.JButton guestPaginationLeft;
    private javax.swing.JButton guestPaginationRight;
    private javax.swing.JSeparator guest_seperator_1;
    private javax.swing.JScrollPane guest_table;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel pageNumber;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel totalRecords;
    private javax.swing.JButton viewHistoryBtn;
    // End of variables declaration//GEN-END:variables
}
