/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hms.view.panels;

import hms.config.Constants;
import hms.util.IconUtil;
import hms.util.ReportUtil;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author vickrant-dev
 */
public class ReportsPanel extends javax.swing.JPanel {

    private JasperPrint currentJasperPrint;
    private final JFileChooser fileChooser;

    /**
     * Creates new form ReportsPanel1
     */
    public ReportsPanel() {
        initComponents();
        setupIcons();
        fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("PDF Files (*.pdf)", "pdf"));
        reportTypeCmb.removeAllItems();
        reportTypeCmb.addItem("Occupancy & Revenue Report");
        reportTypeCmb.addItem("Guest Invoice Report");
        roomTypeCmb.removeAllItems();
        roomTypeCmb.addItem("All");
        roomTypeCmb.addItem(Constants.ROOM_TYPE_SINGLE);
        roomTypeCmb.addItem(Constants.ROOM_TYPE_DOUBLE);
        roomTypeCmb.addItem(Constants.ROOM_TYPE_SUITE);
        roomTypeCmb.addItem(Constants.ROOM_TYPE_DELUXE);
        statusCmb.removeAllItems();
        statusCmb.addItem("All");
        statusCmb.addItem("Paid");
        statusCmb.addItem("Pending");
        reportPreviewPanel.setLayout(new java.awt.BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        guest_seperator_1 = new javax.swing.JSeparator();
        reportTypeCmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        filtersPanel = new hms.theme.RoundedPanel(20);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateRangeFrom = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        dateRangeTo = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        searchBox = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        roomTypeCmb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        statusCmb = new javax.swing.JComboBox<>();
        guest_seperator_2 = new javax.swing.JSeparator();
        generateReportBtn = new javax.swing.JButton();
        exportPdfBtn = new javax.swing.JButton();
        reportPreviewPanel = new hms.theme.RoundedPanel(20);

        heading.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        heading.setText("Reports");

        description.setText("Generate and export system reports");

        reportTypeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Report type:");

        filtersPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("FILTERS");

        jLabel3.setText("Date Range");

        jLabel4.setText("From");

        jLabel5.setText("To");

        jLabel6.setText("Guest Selector");

        searchBtn.setText("Search");

        jLabel7.setText("Room Type");

        roomTypeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Deluxe Suite" }));

        jLabel8.setText("Status");

        statusCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Active", "Inactive" }));

        generateReportBtn.setText("Generate Report");
        generateReportBtn.addActionListener(this::generateReportBtnActionPerformed);

        exportPdfBtn.setText("Export PDF");
        exportPdfBtn.setActionCommand("");
        exportPdfBtn.addActionListener(this::exportPdfBtnActionPerformed);

        javax.swing.GroupLayout filtersPanelLayout = new javax.swing.GroupLayout(filtersPanel);
        filtersPanel.setLayout(filtersPanelLayout);
        filtersPanelLayout.setHorizontalGroup(
            filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomTypeCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateRangeTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(filtersPanelLayout.createSequentialGroup()
                        .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBox, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn))
                    .addComponent(dateRangeFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(filtersPanelLayout.createSequentialGroup()
                        .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filtersPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guest_seperator_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filtersPanelLayout.createSequentialGroup()
                                .addComponent(generateReportBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exportPdfBtn)))))
                .addContainerGap())
        );
        filtersPanelLayout.setVerticalGroup(
            filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateRangeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateRangeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(searchBox))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomTypeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(guest_seperator_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportPdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        reportPreviewPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        javax.swing.GroupLayout reportPreviewPanelLayout = new javax.swing.GroupLayout(reportPreviewPanel);
        reportPreviewPanel.setLayout(reportPreviewPanelLayout);
        reportPreviewPanelLayout.setHorizontalGroup(
            reportPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        reportPreviewPanelLayout.setVerticalGroup(
            reportPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guest_seperator_1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heading)
                            .addComponent(description))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(reportTypeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filtersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reportPreviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(description))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(reportTypeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(guest_seperator_1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportPreviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportBtnActionPerformed
        int reportIndex = reportTypeCmb.getSelectedIndex();
        if (reportIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a report type.",
                "No Report Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String reportName = reportIndex == 0 ? "occupancy_report" : "invoice_report";
        java.util.Date fromDate = dateRangeFrom.getDate();
        java.util.Date toDate = dateRangeTo.getDate();
        Map<String, Object> params = new HashMap<>();
        if (fromDate != null) {
            params.put("start_date", fromDate);
        }
        if (toDate != null) {
            params.put("end_date", toDate);
        }
        if (reportIndex == 0) {
            String roomType = (String) roomTypeCmb.getSelectedItem();
            if (roomType == null || roomType.equals("All")) {
                params.put("room_type", "");
            } else {
                params.put("room_type", roomType);
            }
        }
        String status = (String) statusCmb.getSelectedItem();
        if (status != null && !status.equals("All")) {
            params.put("status", status.toLowerCase());
        }
        String guestName = searchBox.getText().trim();
        if (!guestName.isEmpty()) {
            params.put("guest_name", guestName);
        }
        try {
            JasperReport report = ReportUtil.loadReport(reportName);
            currentJasperPrint = ReportUtil.fillReport(report, params);
            reportPreviewPanel.removeAll();
            JRViewer viewer = new JRViewer(currentJasperPrint);
            reportPreviewPanel.add(viewer, java.awt.BorderLayout.CENTER);
            reportPreviewPanel.revalidate();
            reportPreviewPanel.repaint();
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this,
                "Failed to generate report: " + e.getMessage(),
                "Report Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Unexpected error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReportBtnActionPerformed

    private void exportPdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportPdfBtnActionPerformed
        if (currentJasperPrint == null) {
            JOptionPane.showMessageDialog(this,
                "No report generated yet. Please generate a report first.",
                "No Report", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String path = file.getAbsolutePath();
            if (!path.toLowerCase().endsWith(".pdf")) {
                path += ".pdf";
            }
            try {
                ReportUtil.exportToPdf(currentJasperPrint, path);
                JOptionPane.showMessageDialog(this,
                    "PDF exported to: " + path,
                    "Export Successful", JOptionPane.INFORMATION_MESSAGE);
            } catch (JRException e) {
                JOptionPane.showMessageDialog(this,
                    "Failed to export PDF: " + e.getMessage(),
                    "Export Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_exportPdfBtnActionPerformed


    private void setupIcons() {
        generateReportBtn.setIcon(IconUtil.getRefreshIcon());
        exportPdfBtn.setIcon(IconUtil.getPrintIcon());
        searchBtn.setIcon(IconUtil.getSearchIcon());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateRangeFrom;
    private com.toedter.calendar.JDateChooser dateRangeTo;
    private javax.swing.JLabel description;
    private javax.swing.JButton exportPdfBtn;
    private javax.swing.JPanel filtersPanel;
    private javax.swing.JButton generateReportBtn;
    private javax.swing.JSeparator guest_seperator_1;
    private javax.swing.JSeparator guest_seperator_2;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel reportPreviewPanel;
    private javax.swing.JComboBox<String> reportTypeCmb;
    private javax.swing.JComboBox<String> roomTypeCmb;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> statusCmb;
    // End of variables declaration//GEN-END:variables
}
