/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hms.view.panels;

import hms.model.Reservation;
import java.awt.Frame;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import hms.view.dialogs.NewReservationDialog;
import hms.view.dialogs.GuestCheckInDialog;
import hms.view.dialogs.GuestCheckOutDialog;
import hms.view.dialogs.CancellationDialog;

/**
 *
 * @author vickrant
 */
public class ReservationPanel extends javax.swing.JPanel {

    private List<Reservation> filteredReservations;

    /**
     * Creates new form ReservationPanel
     */
    public ReservationPanel() {
        initComponents();
        setupTable();
    }

    private Reservation getSelectedReservation() {
        int viewRow = reservationsTable.getSelectedRow();
        if (viewRow == -1 || filteredReservations == null) return null;
        return filteredReservations.get(reservationsTable.convertRowIndexToModel(viewRow));
    }

    private void setupTable() {
        reservationsTable.getSelectionModel().addListSelectionListener(e -> {
            boolean hasSelection = reservationsTable.getSelectedRow() != -1;
            checkInBtn.setEnabled(hasSelection);
            checkOutBtn.setEnabled(hasSelection);
            modifyResBtn.setEnabled(hasSelection);
            cancelResBtn.setEnabled(hasSelection);
        });
        checkInBtn.setEnabled(false);
        checkOutBtn.setEnabled(false);
        modifyResBtn.setEnabled(false);
        cancelResBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reservationGroupPanel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        addReservationBtn = new javax.swing.JButton();
        guest_seperator_1 = new javax.swing.JSeparator();
        applyFiltersBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        room_seperator_2 = new javax.swing.JSeparator();
        statusCmb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchBox = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        dateRangeFrom = new com.toedter.calendar.JDateChooser();
        dateRangeTo = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationsTable = new javax.swing.JTable();
        reservationBottomBar = new javax.swing.JPanel();
        checkInBtn = new javax.swing.JButton();
        checkOutBtn = new javax.swing.JButton();
        modifyResBtn = new javax.swing.JButton();
        reservationPaginationLeft = new javax.swing.JButton();
        reservationPaginationRight = new javax.swing.JButton();
        pageNumber9 = new javax.swing.JLabel();
        totalRecords8 = new javax.swing.JLabel();
        cancelResBtn = new javax.swing.JButton();

        heading.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        heading.setText("Reservations");

        description.setText("View reservations and manage them.");

        addReservationBtn.setText("Add Reservation");
        addReservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReservationBtnActionPerformed(evt);
            }
        });

        applyFiltersBtn.setText("Apply Filters");
        applyFiltersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFiltersBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Search by room no.");

        room_seperator_2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        statusCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Types", "Deluxe King Suite", "Standard Double", "Single Economy" }));

        jLabel2.setText("Status");

        jLabel3.setText("Date Range");

        searchBox.setToolTipText("Search by room no.");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        reservationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "RES ID", "GUEST NAME", "ROOM", "CHECK-IN", "CHECK-OUT", "AMOUNT", "STATUS", "CREATED"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reservationsTable);

        reservationBottomBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        checkInBtn.setText("Check-In");
        checkInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInBtnActionPerformed(evt);
            }
        });

        checkOutBtn.setText("Check-Out");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        modifyResBtn.setText("Modify");
        modifyResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyResBtnActionPerformed(evt);
            }
        });

        reservationPaginationLeft.setText("<");
        reservationPaginationLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationPaginationLeftActionPerformed(evt);
            }
        });

        reservationPaginationRight.setText(">");
        reservationPaginationRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationPaginationRightActionPerformed(evt);
            }
        });

        pageNumber9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pageNumber9.setText("Page 1 of 5");

        totalRecords8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalRecords8.setText("Records: 10");

        cancelResBtn.setText("Cancel");
        cancelResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelResBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reservationBottomBarLayout = new javax.swing.GroupLayout(reservationBottomBar);
        reservationBottomBar.setLayout(reservationBottomBarLayout);
        reservationBottomBarLayout.setHorizontalGroup(
            reservationBottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationBottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkInBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyResBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelResBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalRecords8)
                .addGap(18, 18, 18)
                .addComponent(reservationPaginationLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationPaginationRight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pageNumber9)
                .addContainerGap())
        );
        reservationBottomBarLayout.setVerticalGroup(
            reservationBottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationBottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservationBottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageNumber9)
                    .addComponent(reservationPaginationLeft)
                    .addComponent(reservationPaginationRight)
                    .addComponent(totalRecords8)
                    .addComponent(cancelResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout reservationGroupPanelLayout = new javax.swing.GroupLayout(reservationGroupPanel);
        reservationGroupPanel.setLayout(reservationGroupPanelLayout);
        reservationGroupPanelLayout.setHorizontalGroup(
            reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationGroupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(guest_seperator_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(reservationGroupPanelLayout.createSequentialGroup()
                        .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heading)
                            .addComponent(description))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addReservationBtn))
                    .addGroup(reservationGroupPanelLayout.createSequentialGroup()
                        .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(reservationGroupPanelLayout.createSequentialGroup()
                                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room_seperator_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(statusCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(reservationGroupPanelLayout.createSequentialGroup()
                                .addComponent(dateRangeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateRangeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(clearBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(applyFiltersBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(reservationBottomBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        reservationGroupPanelLayout.setVerticalGroup(
            reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationGroupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addReservationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(reservationGroupPanelLayout.createSequentialGroup()
                        .addComponent(heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(description)))
                .addGap(18, 18, 18)
                .addComponent(guest_seperator_1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, reservationGroupPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(room_seperator_2)
                    .addGroup(reservationGroupPanelLayout.createSequentialGroup()
                        .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(reservationGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusCmb)
                            .addComponent(applyFiltersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateRangeFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateRangeTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reservationBottomBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reservationGroupPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reservationGroupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addReservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReservationBtnActionPerformed
        NewReservationDialog d = new NewReservationDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setVisible(true);
    }//GEN-LAST:event_addReservationBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO: reservationController.search(searchBox.getText()); refreshTable();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        searchBox.setText("");
        statusCmb.setSelectedIndex(0);
        dateRangeFrom.setDate(null);
        dateRangeTo.setDate(null);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void applyFiltersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFiltersBtnActionPerformed
        // TODO: reservationController.applyFilters(statusCmb, dateRangeFrom, dateRangeTo); refreshTable();
    }//GEN-LAST:event_applyFiltersBtnActionPerformed

    private void checkInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInBtnActionPerformed
        Reservation selected = getSelectedReservation();
        if (selected == null) return;
        GuestCheckInDialog d = new GuestCheckInDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setTitle("Check-In: " + selected.getDisplayId());
        d.setVisible(true);
    }//GEN-LAST:event_checkInBtnActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        Reservation selected = getSelectedReservation();
        if (selected == null) return;
        GuestCheckOutDialog d = new GuestCheckOutDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setTitle("Check-Out: " + selected.getDisplayId());
        d.setVisible(true);
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void modifyResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyResBtnActionPerformed
        Reservation selected = getSelectedReservation();
        if (selected == null) return;
        NewReservationDialog d = new NewReservationDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setTitle("Modify Reservation: " + selected.getDisplayId());
        d.setVisible(true);
    }//GEN-LAST:event_modifyResBtnActionPerformed

    private void cancelResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelResBtnActionPerformed
        Reservation selected = getSelectedReservation();
        if (selected == null) return;
        CancellationDialog d = new CancellationDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setTitle("Cancel: " + selected.getDisplayId());
        d.setVisible(true);
    }//GEN-LAST:event_cancelResBtnActionPerformed

    private void reservationPaginationLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationPaginationLeftActionPerformed
        // TODO: loadPreviousPage();
    }//GEN-LAST:event_reservationPaginationLeftActionPerformed

    private void reservationPaginationRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationPaginationRightActionPerformed
        // TODO: loadNextPage();
    }//GEN-LAST:event_reservationPaginationRightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReservationBtn;
    private javax.swing.JButton applyFiltersBtn;
    private javax.swing.JButton cancelResBtn;
    private javax.swing.JButton checkInBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JButton clearBtn;
    private com.toedter.calendar.JDateChooser dateRangeFrom;
    private com.toedter.calendar.JDateChooser dateRangeTo;
    private javax.swing.JLabel description;
    private javax.swing.JSeparator guest_seperator_1;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyResBtn;
    private javax.swing.JLabel pageNumber9;
    private javax.swing.JPanel reservationBottomBar;
    private javax.swing.JPanel reservationGroupPanel;
    private javax.swing.JButton reservationPaginationLeft;
    private javax.swing.JButton reservationPaginationRight;
    private javax.swing.JTable reservationsTable;
    private javax.swing.JSeparator room_seperator_2;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> statusCmb;
    private javax.swing.JLabel totalRecords8;
    // End of variables declaration//GEN-END:variables
}
