/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hms.view.panels;

import hms.config.Constants;
import hms.controller.RoomController;
import hms.exception.DatabaseException;
import hms.exception.ValidationException;
import hms.model.Room;
import java.awt.Frame;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import hms.view.dialogs.AddNewRoomDialog;

/**
 *
 * @author vickrant
 */
public class RoomManagementPanel extends javax.swing.JPanel {

    private final RoomController roomController = new RoomController();
    private List<Room> filteredRooms;
    private int currentPage = 0;
    private static final int PAGE_SIZE = 10;

    /**
     * Creates new form RoomManagementPanel
     */
    public RoomManagementPanel() {
        initComponents();
        setupTable();
        setupPaginationListeners();
        loadRooms();
    }

    private Room getSelectedRoom() {
        int viewRow = roomManagementTable.getSelectedRow();
        if (viewRow == -1 || filteredRooms == null) return null;
        return filteredRooms.get(roomManagementTable.convertRowIndexToModel(viewRow));
    }

    private void loadRooms() {
        try {
            filteredRooms = roomController.getAllRooms();
            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Failed to load rooms: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void applyPagination() {
        int total = filteredRooms.size();
        int totalPages = Math.max(1, (int) Math.ceil((double) total / PAGE_SIZE));
        if (currentPage >= totalPages) currentPage = totalPages - 1;
        if (currentPage < 0) currentPage = 0;

        int from = currentPage * PAGE_SIZE;
        int to = Math.min(from + PAGE_SIZE, total);
        List<Room> page = from < total ? filteredRooms.subList(from, to) : List.of();

        String[][] data = new String[page.size()][7];
        for (int i = 0; i < page.size(); i++) {
            Room r = page.get(i);
            data[i][0] = String.valueOf(r.getRoomId());
            data[i][1] = r.getRoomNumber();
            data[i][2] = r.getRoomType();
            data[i][3] = String.valueOf(r.getFloor());
            data[i][4] = String.format("%.2f", r.getBasePrice());
            data[i][5] = String.valueOf(r.getCapacity());
            data[i][6] = r.getStatus();
        }

        roomManagementTable.setModel(new javax.swing.table.DefaultTableModel(data, new String[]{
            "#", "Room No.", "Room Type", "Floor", "Base Price", "Capacity", "Status"
        }) {
            boolean[] canEdit = {false, false, false, false, false, true, true};
            @Override public boolean isCellEditable(int row, int col) { return canEdit[col]; }
        });

        pageNumber2.setText("Page " + (currentPage + 1) + " of " + totalPages);
        totalRecords1.setText("Records: " + total);
    }

    private void setupPaginationListeners() {
        roomManagementPaginationLeft.addActionListener(e -> {
            if (currentPage > 0) { currentPage--; applyPagination(); }
        });
        roomManagementPaginationRight.addActionListener(e -> {
            int totalPages = Math.max(1, (int) Math.ceil((double) filteredRooms.size() / PAGE_SIZE));
            if (currentPage < totalPages - 1) { currentPage++; applyPagination(); }
        });
    }

    private void setupTable() {
        roomManagementTable.getSelectionModel().addListSelectionListener(e -> {
            boolean hasSelection = roomManagementTable.getSelectedRow() != -1;
            editRoomBtn.setEnabled(hasSelection);
            deleteRoomBtn.setEnabled(hasSelection);
            markMaintBtn.setEnabled(hasSelection);
            markAvailBtn.setEnabled(hasSelection);
        });
        editRoomBtn.setEnabled(false);
        deleteRoomBtn.setEnabled(false);
        markMaintBtn.setEnabled(false);
        markAvailBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomManagementPanelGroup = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        addRoomBtn = new javax.swing.JButton();
        room_seperator_1 = new javax.swing.JSeparator();
        searchBox = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        room_seperator_2 = new javax.swing.JSeparator();
        statusCmb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceRangeFrom = new javax.swing.JTextField();
        priceRangeTo = new javax.swing.JTextField();
        capacityCmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        applyFiltersBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomManagementTable = new javax.swing.JTable();
        bottomBar = new javax.swing.JPanel();
        editRoomBtn = new javax.swing.JButton();
        deleteRoomBtn = new javax.swing.JButton();
        markMaintBtn = new javax.swing.JButton();
        roomManagementPaginationLeft = new javax.swing.JButton();
        roomManagementPaginationRight = new javax.swing.JButton();
        pageNumber2 = new javax.swing.JLabel();
        totalRecords1 = new javax.swing.JLabel();
        markAvailBtn = new javax.swing.JButton();

        heading.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        heading.setText("Room Mangement");

        description.setText("Manage property inventory, pricing and operational status");

        addRoomBtn.setText("Add Room");
        addRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomBtnActionPerformed(evt);
            }
        });

        searchBox.setToolTipText("Search by room no.");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Search by room no.");

        room_seperator_2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        statusCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Types", "Deluxe King Suite", "Standard Double", "Single Economy" }));

        jLabel2.setText("Status");

        jLabel3.setText("Price Range (LKR)");

        priceRangeFrom.setToolTipText("Min");

        priceRangeTo.setToolTipText("Max");

        capacityCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "1", "2", "3", "4" }));

        jLabel4.setText("Capacity");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        applyFiltersBtn.setText("Apply Filters");
        applyFiltersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFiltersBtnActionPerformed(evt);
            }
        });

        roomManagementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Room No.", "Room Type", "Floor", "Base Price", "Capacity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(roomManagementTable);

        bottomBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        editRoomBtn.setText("Edit");
        editRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRoomBtnActionPerformed(evt);
            }
        });

        deleteRoomBtn.setText("Delete");
        deleteRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoomBtnActionPerformed(evt);
            }
        });

        markMaintBtn.setText("Mark Maintenance");
        markMaintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markMaintBtnActionPerformed(evt);
            }
        });

        roomManagementPaginationLeft.setText("<");

        roomManagementPaginationRight.setText(">");

        pageNumber2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pageNumber2.setText("Page 1 of 5");

        totalRecords1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalRecords1.setText("Records: 20");

        markAvailBtn.setText("Mark Available");
        markAvailBtn.setToolTipText("");
        markAvailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAvailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomBarLayout = new javax.swing.GroupLayout(bottomBar);
        bottomBar.setLayout(bottomBarLayout);
        bottomBarLayout.setHorizontalGroup(
            bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editRoomBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteRoomBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markMaintBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markAvailBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalRecords1)
                .addGap(18, 18, 18)
                .addComponent(roomManagementPaginationLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomManagementPaginationRight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pageNumber2)
                .addContainerGap())
        );
        bottomBarLayout.setVerticalGroup(
            bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markMaintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageNumber2)
                    .addComponent(roomManagementPaginationLeft)
                    .addComponent(roomManagementPaginationRight)
                    .addComponent(totalRecords1)
                    .addComponent(markAvailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roomManagementPanelGroupLayout = new javax.swing.GroupLayout(roomManagementPanelGroup);
        roomManagementPanelGroup.setLayout(roomManagementPanelGroupLayout);
        roomManagementPanelGroupLayout.setHorizontalGroup(
            roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomManagementPanelGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(room_seperator_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomManagementPanelGroupLayout.createSequentialGroup()
                        .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heading)
                            .addComponent(description))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomManagementPanelGroupLayout.createSequentialGroup()
                        .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(roomManagementPanelGroupLayout.createSequentialGroup()
                                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room_seperator_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(statusCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roomManagementPanelGroupLayout.createSequentialGroup()
                                .addComponent(priceRangeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priceRangeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(roomManagementPanelGroupLayout.createSequentialGroup()
                                .addComponent(capacityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(clearBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(applyFiltersBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bottomBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roomManagementPanelGroupLayout.setVerticalGroup(
            roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomManagementPanelGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roomManagementPanelGroupLayout.createSequentialGroup()
                        .addComponent(heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(description)))
                .addGap(18, 18, 18)
                .addComponent(room_seperator_1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roomManagementPanelGroupLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(room_seperator_2)
                    .addGroup(roomManagementPanelGroupLayout.createSequentialGroup()
                        .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(roomManagementPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusCmb)
                            .addComponent(capacityCmb)
                            .addComponent(priceRangeFrom)
                            .addComponent(priceRangeTo)
                            .addComponent(applyFiltersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottomBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomManagementPanelGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roomManagementPanelGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRoomBtnActionPerformed
        Room selected = getSelectedRoom();
        if (selected == null) return;
        AddNewRoomDialog d = new AddNewRoomDialog((Frame) SwingUtilities.getWindowAncestor(this), true, selected);
        d.setTitle("Edit Room: " + selected.getRoomNumber());
        d.setVisible(true);
        loadRooms();
    }//GEN-LAST:event_editRoomBtnActionPerformed

    private void addRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomBtnActionPerformed
        AddNewRoomDialog d = new AddNewRoomDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setVisible(true);
        loadRooms();
    }//GEN-LAST:event_addRoomBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String keyword = searchBox.getText().trim();
        try {
            filteredRooms = keyword.isEmpty()
                ? roomController.getAllRooms()
                : roomController.searchRooms(keyword);
            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Search failed: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        searchBox.setText("");
        statusCmb.setSelectedIndex(0);
        priceRangeFrom.setText("");
        priceRangeTo.setText("");
        capacityCmb.setSelectedIndex(0);
        loadRooms();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void applyFiltersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFiltersBtnActionPerformed
        try {
            String status = (String) statusCmb.getSelectedItem();
            String capacity = (String) capacityCmb.getSelectedItem();
            String priceFrom = priceRangeFrom.getText().trim();
            String priceTo = priceRangeTo.getText().trim();

            boolean typeActive = status != null && !status.equals("All Types");

            List<Room> filtered;
            if (typeActive) {
                filtered = roomController.filterByType(status);
            } else {
                filtered = roomController.getAllRooms();
            }

            String cap = capacity;
            filtered = filtered.stream()
                .filter(r -> cap == null || cap.equals("Any") || cap.isEmpty()
                    || r.getCapacity() == Integer.parseInt(cap))
                .filter(r -> priceFrom.isEmpty() || r.getBasePrice() >= Double.parseDouble(priceFrom))
                .filter(r -> priceTo.isEmpty() || r.getBasePrice() <= Double.parseDouble(priceTo))
                .collect(Collectors.toList());

            filteredRooms = filtered;
            currentPage = 0;
            applyPagination();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Filter error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_applyFiltersBtnActionPerformed

    private void deleteRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomBtnActionPerformed
        Room selected = getSelectedRoom();
        if (selected == null) return;
        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete room " + selected.getRoomNumber() + "?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                roomController.deleteRoom(selected.getRoomId());
                loadRooms();
            } catch (DatabaseException e) {
                JOptionPane.showMessageDialog(this, "Failed to delete room: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteRoomBtnActionPerformed

    private void markMaintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markMaintBtnActionPerformed
        Room selected = getSelectedRoom();
        if (selected == null) return;
        try {
            roomController.markForMaintenance(selected.getRoomId());
            loadRooms();
        } catch (ValidationException | DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Failed to update status: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_markMaintBtnActionPerformed

    private void markAvailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAvailBtnActionPerformed
        Room selected = getSelectedRoom();
        if (selected == null) return;
        try {
            roomController.updateRoomStatus(selected.getRoomId(), Constants.ROOM_STATUS_AVAILABLE);
            loadRooms();
        } catch (ValidationException | DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Failed to update status: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_markAvailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomBtn;
    private javax.swing.JButton applyFiltersBtn;
    private javax.swing.JPanel bottomBar;
    private javax.swing.JComboBox<String> capacityCmb;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteRoomBtn;
    private javax.swing.JLabel description;
    private javax.swing.JButton editRoomBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton markAvailBtn;
    private javax.swing.JButton markMaintBtn;
    private javax.swing.JLabel pageNumber2;
    private javax.swing.JTextField priceRangeFrom;
    private javax.swing.JTextField priceRangeTo;
    private javax.swing.JButton roomManagementPaginationLeft;
    private javax.swing.JButton roomManagementPaginationRight;
    private javax.swing.JPanel roomManagementPanelGroup;
    private javax.swing.JTable roomManagementTable;
    private javax.swing.JSeparator room_seperator_1;
    private javax.swing.JSeparator room_seperator_2;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> statusCmb;
    private javax.swing.JLabel totalRecords1;
    // End of variables declaration//GEN-END:variables
}
