/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hms.view.panels;

import hms.controller.ServiceController;
import hms.exception.DatabaseException;
import hms.exception.ValidationException;
import hms.model.Service;
import java.awt.Frame;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import hms.view.dialogs.AddNewService;
import hms.view.dialogs.ServiceBookingDialog;

/**
 *
 * @author vickrant-dev
 */
public class ServicePanel extends javax.swing.JPanel {

    private final ServiceController serviceController = new ServiceController();
    private List<Service> filteredServices;
    private int currentPage = 0;
    private static final int PAGE_SIZE = 10;

    /**
     * Creates new form ServicePanel
     */
    public ServicePanel() {
        initComponents();
        setupTable();
        loadServices();
    }

    private void loadServices() {
        try {
            filteredServices = serviceController.getAllServices();
            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Failed to load services: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void applyPagination() {
        int total = filteredServices.size();
        int totalPages = Math.max(1, (int) Math.ceil((double) total / PAGE_SIZE));
        if (currentPage >= totalPages) currentPage = totalPages - 1;
        if (currentPage < 0) currentPage = 0;

        int from = currentPage * PAGE_SIZE;
        int to = Math.min(from + PAGE_SIZE, total);
        List<Service> page = from < total ? filteredServices.subList(from, to) : List.of();

        String[][] data = new String[page.size()][6];
        for (int i = 0; i < page.size(); i++) {
            Service s = page.get(i);
            data[i][0] = String.valueOf(s.getServiceId());
            data[i][1] = s.getServiceName();
            data[i][2] = s.getServiceType();
            data[i][3] = String.format("%.2f", s.getPrice());
            data[i][4] = s.isAvailable() ? "Yes" : "No";
            data[i][5] = "-";
        }

        serviceCatalogTable.setModel(new javax.swing.table.DefaultTableModel(data, new String[]{
            "#", "SERVICE NAME", "SERVICE TYPE", "PRICE", "AVAILABLE", "TOTAL BOOKINGS"
        }) {
            boolean[] canEdit = {false, false, false, false, false, false};
            @Override public boolean isCellEditable(int row, int col) { return canEdit[col]; }
        });

        pageNumber2.setText("Page " + (currentPage + 1) + " of " + totalPages);
        totalRecords1.setText("Records: " + total);
    }

    private Service getSelectedService() {
        int viewRow = serviceCatalogTable.getSelectedRow();
        if (viewRow == -1 || filteredServices == null) return null;
        return filteredServices.get(serviceCatalogTable.convertRowIndexToModel(viewRow));
    }

    private void setupTable() {
        serviceCatalogTable.getSelectionModel().addListSelectionListener(e -> {
            boolean hasSelection = serviceCatalogTable.getSelectedRow() != -1;
            editServiceBtn.setEnabled(hasSelection);
            deleteServiceBtn.setEnabled(hasSelection);
            toggleAvailBtn.setEnabled(hasSelection);
            bookServiceBtn.setEnabled(hasSelection);
        });
        editServiceBtn.setEnabled(false);
        deleteServiceBtn.setEnabled(false);
        toggleAvailBtn.setEnabled(false);
        bookServiceBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        servicePanelGroup = new javax.swing.JPanel();
        room_seperator_1 = new javax.swing.JSeparator();
        addServiceBtn = new javax.swing.JButton();
        description = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        applyFiltersBtn = new javax.swing.JButton();
        searchBox = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        availabilityCmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serviceTypeCmb = new javax.swing.JComboBox<>();
        room_seperator_2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceCatalogTable = new javax.swing.JTable();
        bottomBar = new javax.swing.JPanel();
        editServiceBtn = new javax.swing.JButton();
        deleteServiceBtn = new javax.swing.JButton();
        toggleAvailBtn = new javax.swing.JButton();
        serviceCatalogPaginationLeft = new javax.swing.JButton();
        serviceCatalogPaginationRight = new javax.swing.JButton();
        pageNumber2 = new javax.swing.JLabel();
        totalRecords1 = new javax.swing.JLabel();
        bookServiceBtn = new javax.swing.JButton();

        addServiceBtn.setText("Add Service");
        addServiceBtn.addActionListener(this::addServiceBtnActionPerformed);

        description.setText("Manage property-wide amenities and additional guest services.");

        heading.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        heading.setText("Service Catalog");

        jLabel1.setText("Search catalog");

        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        applyFiltersBtn.setText("Apply Filters");
        applyFiltersBtn.addActionListener(this::applyFiltersBtnActionPerformed);

        searchBox.setToolTipText("Search by room no.");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(this::clearBtnActionPerformed);

        availabilityCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Available", "Unavailable" }));

        jLabel3.setText("Availability");

        jLabel2.setText("Service type");

        serviceTypeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Deluxe King Suite", "Standard Double", "Single Economy" }));

        room_seperator_2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        serviceCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "SERVICE NAME", "SERVICE TYPE", "PRICE", "AVAILABLE", "TOTAL BOOKINGS"
            }
        ));
        jScrollPane1.setViewportView(serviceCatalogTable);

        bottomBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        editServiceBtn.setText("Edit");
        editServiceBtn.addActionListener(this::editServiceBtnActionPerformed);

        deleteServiceBtn.setText("Delete");
        deleteServiceBtn.addActionListener(this::deleteServiceBtnActionPerformed);

        toggleAvailBtn.setText("Toggle Availability");
        toggleAvailBtn.addActionListener(this::toggleAvailBtnActionPerformed);

        serviceCatalogPaginationLeft.setText("<");
        serviceCatalogPaginationLeft.setActionCommand("");
        serviceCatalogPaginationLeft.addActionListener(this::serviceCatalogPaginationLeftActionPerformed);

        serviceCatalogPaginationRight.setText(">");
        serviceCatalogPaginationRight.addActionListener(this::serviceCatalogPaginationRightActionPerformed);

        pageNumber2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pageNumber2.setText("Page 1 of 5");

        totalRecords1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalRecords1.setText("Records: 20");

        bookServiceBtn.setText("Book for Reservation");
        bookServiceBtn.setToolTipText("");
        bookServiceBtn.addActionListener(this::bookServiceBtnActionPerformed);

        javax.swing.GroupLayout bottomBarLayout = new javax.swing.GroupLayout(bottomBar);
        bottomBar.setLayout(bottomBarLayout);
        bottomBarLayout.setHorizontalGroup(
            bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editServiceBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteServiceBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleAvailBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookServiceBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalRecords1)
                .addGap(18, 18, 18)
                .addComponent(serviceCatalogPaginationLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceCatalogPaginationRight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pageNumber2)
                .addContainerGap())
        );
        bottomBarLayout.setVerticalGroup(
            bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleAvailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageNumber2)
                    .addComponent(serviceCatalogPaginationLeft)
                    .addComponent(serviceCatalogPaginationRight)
                    .addComponent(totalRecords1)
                    .addComponent(bookServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout servicePanelGroupLayout = new javax.swing.GroupLayout(servicePanelGroup);
        servicePanelGroup.setLayout(servicePanelGroupLayout);
        servicePanelGroupLayout.setHorizontalGroup(
            servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servicePanelGroupLayout.createSequentialGroup()
                        .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(servicePanelGroupLayout.createSequentialGroup()
                                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room_seperator_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(serviceTypeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(servicePanelGroupLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(servicePanelGroupLayout.createSequentialGroup()
                                .addComponent(availabilityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(clearBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(applyFiltersBtn))))
                    .addComponent(room_seperator_1)
                    .addGroup(servicePanelGroupLayout.createSequentialGroup()
                        .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heading)
                            .addComponent(description))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addServiceBtn))
                    .addComponent(jScrollPane1)
                    .addComponent(bottomBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        servicePanelGroupLayout.setVerticalGroup(
            servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(servicePanelGroupLayout.createSequentialGroup()
                        .addComponent(heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(description)))
                .addGap(18, 18, 18)
                .addComponent(room_seperator_1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, servicePanelGroupLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(room_seperator_2)
                    .addGroup(servicePanelGroupLayout.createSequentialGroup()
                        .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serviceTypeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(applyFiltersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(servicePanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(availabilityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottomBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(servicePanelGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(servicePanelGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editServiceBtnActionPerformed
        Service selected = getSelectedService();
        if (selected == null) return;
        AddNewService d = new AddNewService((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setTitle("Edit Service: " + selected.getServiceName());
        d.setVisible(true);
        loadServices();
    }//GEN-LAST:event_editServiceBtnActionPerformed

    private void addServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServiceBtnActionPerformed
        AddNewService d = new AddNewService((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setVisible(true);
        loadServices();
    }//GEN-LAST:event_addServiceBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String keyword = searchBox.getText().trim().toLowerCase();
        try {
            filteredServices = keyword.isEmpty()
                ? serviceController.getAllServices()
                : serviceController.getAllServices().stream()
                    .filter(s -> s.getServiceName().toLowerCase().contains(keyword)
                        || s.getServiceType().toLowerCase().contains(keyword))
                    .collect(Collectors.toList());
            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Search failed: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        searchBox.setText("");
        serviceTypeCmb.setSelectedIndex(0);
        availabilityCmb.setSelectedIndex(0);
        loadServices();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void applyFiltersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFiltersBtnActionPerformed
        try {
            List<Service> all = serviceController.getAllServices();
            String type = (String) serviceTypeCmb.getSelectedItem();
            String avail = (String) availabilityCmb.getSelectedItem();

            filteredServices = all.stream()
                .filter(s -> type == null || type.equals("All") || s.getServiceType().equals(type))
                .filter(s -> avail == null || avail.equals("All")
                    || (avail.equals("Available") && s.isAvailable())
                    || (avail.equals("Unavailable") && !s.isAvailable()))
                .collect(Collectors.toList());

            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Filter failed: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_applyFiltersBtnActionPerformed

    private void deleteServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteServiceBtnActionPerformed
        Service selected = getSelectedService();
        if (selected == null) return;
        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete service " + selected.getServiceName() + "?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                serviceController.deleteService(selected.getServiceId());
                loadServices();
            } catch (DatabaseException e) {
                JOptionPane.showMessageDialog(this, "Delete failed: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteServiceBtnActionPerformed

    private void toggleAvailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAvailBtnActionPerformed
        Service selected = getSelectedService();
        if (selected == null) return;
        try {
            boolean newState = !selected.isAvailable();
            serviceController.toggleAvailability(selected.getServiceId());
            loadServices();
            JOptionPane.showMessageDialog(this, selected.getServiceName()
                + " toggled to " + (newState ? "Available" : "Unavailable"));
        } catch (ValidationException | DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Toggle failed: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_toggleAvailBtnActionPerformed

    private void bookServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookServiceBtnActionPerformed
        Service selected = getSelectedService();
        if (selected == null) return;
        ServiceBookingDialog d = new ServiceBookingDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setTitle("Book Service: " + selected.getServiceName());
        d.setVisible(true);
        loadServices();
    }//GEN-LAST:event_bookServiceBtnActionPerformed

    private void serviceCatalogPaginationLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCatalogPaginationLeftActionPerformed
        if (currentPage > 0) { currentPage--; applyPagination(); }
    }//GEN-LAST:event_serviceCatalogPaginationLeftActionPerformed

    private void serviceCatalogPaginationRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCatalogPaginationRightActionPerformed
        int totalPages = Math.max(1, (int) Math.ceil((double) filteredServices.size() / PAGE_SIZE));
        if (currentPage < totalPages - 1) { currentPage++; applyPagination(); }
    }//GEN-LAST:event_serviceCatalogPaginationRightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addServiceBtn;
    private javax.swing.JButton applyFiltersBtn;
    private javax.swing.JComboBox<String> availabilityCmb;
    private javax.swing.JButton bookServiceBtn;
    private javax.swing.JPanel bottomBar;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteServiceBtn;
    private javax.swing.JLabel description;
    private javax.swing.JButton editServiceBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pageNumber2;
    private javax.swing.JSeparator room_seperator_1;
    private javax.swing.JSeparator room_seperator_2;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton serviceCatalogPaginationLeft;
    private javax.swing.JButton serviceCatalogPaginationRight;
    private javax.swing.JTable serviceCatalogTable;
    private javax.swing.JPanel servicePanelGroup;
    private javax.swing.JComboBox<String> serviceTypeCmb;
    private javax.swing.JButton toggleAvailBtn;
    private javax.swing.JLabel totalRecords1;
    // End of variables declaration//GEN-END:variables
}
