/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hms.view.panels;

import hms.controller.StaffController;
import hms.exception.DatabaseException;
import hms.exception.ValidationException;
import hms.model.Staff;
import java.awt.Frame;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import hms.view.dialogs.AddNewStaffDialog;

/**
 *
 * @author vickrant-dev
 */
public class StaffPanel extends javax.swing.JPanel {

    private final StaffController staffController = new StaffController();
    private List<Staff> filteredStaff;
    private int currentPage = 0;
    private static final int PAGE_SIZE = 10;

    /**
     * Creates new form StaffPanel
     */
    public StaffPanel() {
        initComponents();
        setupTable();
        setupPaginationListeners();
        loadStaff();
    }

    private void setupPaginationListeners() {
        staffPaginationLeft.addActionListener(e -> {
            if (currentPage > 0) { currentPage--; applyPagination(); }
        });
        staffPaginationRight.addActionListener(e -> {
            int totalPages = Math.max(1, (int) Math.ceil((double) filteredStaff.size() / PAGE_SIZE));
            if (currentPage < totalPages - 1) { currentPage++; applyPagination(); }
        });
    }

    private void loadStaff() {
        try {
            filteredStaff = staffController.getAllStaff();
            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Failed to load staff: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void applyPagination() {
        int total = filteredStaff.size();
        int totalPages = Math.max(1, (int) Math.ceil((double) total / PAGE_SIZE));
        if (currentPage >= totalPages) currentPage = totalPages - 1;
        if (currentPage < 0) currentPage = 0;

        int from = currentPage * PAGE_SIZE;
        int to = Math.min(from + PAGE_SIZE, total);
        List<Staff> page = from < total ? filteredStaff.subList(from, to) : List.of();

        String[][] data = new String[page.size()][8];
        for (int i = 0; i < page.size(); i++) {
            Staff s = page.get(i);
            data[i][0] = String.valueOf(s.getStaffId());
            data[i][1] = s.getFirstName();
            data[i][2] = s.getLastName();
            data[i][3] = s.getEmail();
            data[i][4] = s.getPhone();
            data[i][5] = s.getPosition();
            data[i][6] = s.getDepartment();
            data[i][7] = String.format("%.2f", s.getSalary());
        }

        staffDirectoryTable.setModel(new javax.swing.table.DefaultTableModel(data, new String[]{
            "#", "First Name", "Last Name", "Email", "Phone", "Position", "Department", "Salary"
        }) {
            boolean[] canEdit = {false, false, false, false, false, false, false, false};
            @Override public boolean isCellEditable(int row, int col) { return canEdit[col]; }
        });

        pageNumber2.setText("Page " + (currentPage + 1) + " of " + totalPages);
        totalRecords1.setText("Records: " + total);
    }

    private Staff getSelectedStaff() {
        int viewRow = staffDirectoryTable.getSelectedRow();
        if (viewRow == -1 || filteredStaff == null) return null;
        return filteredStaff.get(staffDirectoryTable.convertRowIndexToModel(viewRow));
    }

    private void setupTable() {
        staffDirectoryTable.getSelectionModel().addListSelectionListener(e -> {
            boolean hasSelection = staffDirectoryTable.getSelectedRow() != -1;
            editStaffBtn.setEnabled(hasSelection);
            deleteStaffBtn.setEnabled(hasSelection);
        });
        editStaffBtn.setEnabled(false);
        deleteStaffBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffPanelGroup = new javax.swing.JPanel();
        room_seperator_1 = new javax.swing.JSeparator();
        addStaffBtn = new javax.swing.JButton();
        description = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        searchBox = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        positionCmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        departmentCmb = new javax.swing.JComboBox<>();
        room_seperator_2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        applyFiltersBtn = new javax.swing.JButton();
        statusCmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffDirectoryTable = new javax.swing.JTable();
        bottomBar = new javax.swing.JPanel();
        editStaffBtn = new javax.swing.JButton();
        deleteStaffBtn = new javax.swing.JButton();
        staffPaginationLeft = new javax.swing.JButton();
        staffPaginationRight = new javax.swing.JButton();
        pageNumber2 = new javax.swing.JLabel();
        totalRecords1 = new javax.swing.JLabel();

        addStaffBtn.setText("Add Staff");
        addStaffBtn.addActionListener(this::addStaffBtnActionPerformed);

        description.setText("Manage employees, roles, and departmental assignments across the property.");

        heading.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        heading.setText("Staff Directory");

        searchBox.setToolTipText("Search by room no.");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(this::clearBtnActionPerformed);

        positionCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Available", "Unavailable" }));

        jLabel3.setText("Position");

        jLabel2.setText("Department");

        departmentCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Deluxe King Suite", "Standard Double", "Single Economy" }));

        room_seperator_2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Search catalog");

        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        applyFiltersBtn.setText("Apply Filters");
        applyFiltersBtn.addActionListener(this::applyFiltersBtnActionPerformed);

        statusCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Available", "Unavailable" }));

        jLabel4.setText("Status");

        staffDirectoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "First Name", "Last Name", "Email", "Phone", "Position", "Department", "Salary"
            }
        ));
        jScrollPane1.setViewportView(staffDirectoryTable);

        bottomBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        editStaffBtn.setText("Edit");
        editStaffBtn.addActionListener(this::editStaffBtnActionPerformed);

        deleteStaffBtn.setText("Delete");
        deleteStaffBtn.addActionListener(this::deleteStaffBtnActionPerformed);

        staffPaginationLeft.setText("<");

        staffPaginationRight.setText(">");

        pageNumber2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pageNumber2.setText("Page 1 of 5");

        totalRecords1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalRecords1.setText("Records: 20");

        javax.swing.GroupLayout bottomBarLayout = new javax.swing.GroupLayout(bottomBar);
        bottomBar.setLayout(bottomBarLayout);
        bottomBarLayout.setHorizontalGroup(
            bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editStaffBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteStaffBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalRecords1)
                .addGap(18, 18, 18)
                .addComponent(staffPaginationLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffPaginationRight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pageNumber2)
                .addContainerGap())
        );
        bottomBarLayout.setVerticalGroup(
            bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageNumber2)
                    .addComponent(staffPaginationLeft)
                    .addComponent(staffPaginationRight)
                    .addComponent(totalRecords1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout staffPanelGroupLayout = new javax.swing.GroupLayout(staffPanelGroup);
        staffPanelGroup.setLayout(staffPanelGroupLayout);
        staffPanelGroupLayout.setHorizontalGroup(
            staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(room_seperator_1)
                    .addGroup(staffPanelGroupLayout.createSequentialGroup()
                        .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heading)
                            .addComponent(description))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addStaffBtn))
                    .addGroup(staffPanelGroupLayout.createSequentialGroup()
                        .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(staffPanelGroupLayout.createSequentialGroup()
                                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room_seperator_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(departmentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(staffPanelGroupLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(staffPanelGroupLayout.createSequentialGroup()
                                .addComponent(statusCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(clearBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(applyFiltersBtn))))
                    .addComponent(bottomBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        staffPanelGroupLayout.setVerticalGroup(
            staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(staffPanelGroupLayout.createSequentialGroup()
                        .addComponent(heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(description)))
                .addGap(18, 18, 18)
                .addComponent(room_seperator_1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, staffPanelGroupLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(room_seperator_2)
                    .addGroup(staffPanelGroupLayout.createSequentialGroup()
                        .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(departmentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(applyFiltersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(staffPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(positionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(statusCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottomBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffPanelGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffPanelGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStaffBtnActionPerformed
        Staff selected = getSelectedStaff();
        if (selected == null) return;
        AddNewStaffDialog d = new AddNewStaffDialog((Frame) SwingUtilities.getWindowAncestor(this), true, selected);
        d.setTitle("Edit Staff: " + selected.getFirstName() + " " + selected.getLastName());
        d.setVisible(true);
        loadStaff();
    }//GEN-LAST:event_editStaffBtnActionPerformed

    private void deleteStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStaffBtnActionPerformed
        Staff selected = getSelectedStaff();
        if (selected == null) return;
        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete staff " + selected.getFirstName() + " " + selected.getLastName() + "?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                staffController.deleteStaff(selected.getStaffId());
                loadStaff();
            } catch (DatabaseException e) {
                JOptionPane.showMessageDialog(this, "Delete failed: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteStaffBtnActionPerformed

    private void addStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffBtnActionPerformed
        AddNewStaffDialog d = new AddNewStaffDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        d.setVisible(true);
        loadStaff();
    }//GEN-LAST:event_addStaffBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String keyword = searchBox.getText().trim().toLowerCase();
        try {
            filteredStaff = keyword.isEmpty()
                ? staffController.getAllStaff()
                : staffController.getAllStaff().stream()
                    .filter(s -> s.getFirstName().toLowerCase().contains(keyword)
                        || s.getLastName().toLowerCase().contains(keyword)
                        || s.getEmail().toLowerCase().contains(keyword)
                        || s.getPhone().contains(keyword))
                    .collect(Collectors.toList());
            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Search failed: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        searchBox.setText("");
        departmentCmb.setSelectedIndex(0);
        positionCmb.setSelectedIndex(0);
        statusCmb.setSelectedIndex(0);
        loadStaff();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void applyFiltersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFiltersBtnActionPerformed
        try {
            List<Staff> all = staffController.getAllStaff();
            String dept = (String) departmentCmb.getSelectedItem();
            String pos = (String) positionCmb.getSelectedItem();
            String status = (String) statusCmb.getSelectedItem();

            filteredStaff = all.stream()
                .filter(s -> dept == null || dept.equals("All") || s.getDepartment().equalsIgnoreCase(dept))
                .filter(s -> pos == null || pos.equals("All") || s.getPosition().equalsIgnoreCase(pos))
                .filter(s -> status == null || status.equals("All")
                    || (status.equals("Available") && "Active".equalsIgnoreCase(s.getStatus()))
                    || (status.equals("Unavailable") && !"Active".equalsIgnoreCase(s.getStatus())))
                .collect(Collectors.toList());

            currentPage = 0;
            applyPagination();
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, "Filter failed: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_applyFiltersBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffBtn;
    private javax.swing.JButton applyFiltersBtn;
    private javax.swing.JPanel bottomBar;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteStaffBtn;
    private javax.swing.JComboBox<String> departmentCmb;
    private javax.swing.JLabel description;
    private javax.swing.JButton editStaffBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pageNumber2;
    private javax.swing.JComboBox<String> positionCmb;
    private javax.swing.JSeparator room_seperator_1;
    private javax.swing.JSeparator room_seperator_2;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable staffDirectoryTable;
    private javax.swing.JButton staffPaginationLeft;
    private javax.swing.JButton staffPaginationRight;
    private javax.swing.JPanel staffPanelGroup;
    private javax.swing.JComboBox<String> statusCmb;
    private javax.swing.JLabel totalRecords1;
    // End of variables declaration//GEN-END:variables
}
