/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package hms.view.dialogs;

import hms.controller.ReservationController;
import hms.exception.DatabaseException;
import hms.exception.ValidationException;
import hms.model.Reservation;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author vickrant
 */
public class CancellationDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CancellationDialog.class.getName());

    private final ReservationController reservationController = new ReservationController();
    private Reservation reservation;

    /**
     * Creates new form CancellationDialog
     */
    public CancellationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Creates new form CancellationDialog with reservation data.
     */
    public CancellationDialog(java.awt.Frame parent, boolean modal, Reservation reservation) {
        super(parent, modal);
        initComponents();
        this.reservation = reservation;
        setTitle("Cancel: " + reservation.getDisplayId());
        guestFullName.setText(reservation.getGuest().getFirstName() + " " + reservation.getGuest().getLastName());
        roomNumber.setText(reservation.getRoom().getRoomNumber());
        roomType.setText(reservation.getRoom().getRoomType());
        stayPeriodRange.setText(reservation.getCheckInDate() + " to " + reservation.getCheckOutDate());
        long nights = ChronoUnit.DAYS.between(reservation.getCheckInDate(), reservation.getCheckOutDate());
        duration.setText(nights + " night(s)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        room_no_box = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        roomNumber = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        roomType = new javax.swing.JLabel();
        stay_period_box = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        stayPeriodRange = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        guest_name_box = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        guestFullName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cancellationReason_1 = new javax.swing.JCheckBox();
        cancellationReason_2 = new javax.swing.JCheckBox();
        cancellationReason_3 = new javax.swing.JCheckBox();
        cancellationReason_4 = new javax.swing.JCheckBox();
        cancellationReason_4_description = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cancellationNotes = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        confirmCancellationBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cancel Reservation - RES-20260625-001");

        room_no_box.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        jLabel5.setText("Room");

        roomNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomNumber.setText("402");

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        roomType.setBackground(new java.awt.Color(0, 0, 0));
        roomType.setText("EXECUTIVE SUIT");

        javax.swing.GroupLayout room_no_boxLayout = new javax.swing.GroupLayout(room_no_box);
        room_no_box.setLayout(room_no_boxLayout);
        room_no_boxLayout.setHorizontalGroup(
            room_no_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room_no_boxLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(room_no_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(room_no_boxLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(room_no_boxLayout.createSequentialGroup()
                        .addComponent(roomNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roomType)))
                .addContainerGap())
        );
        room_no_boxLayout.setVerticalGroup(
            room_no_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room_no_boxLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(room_no_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNumber)
                    .addComponent(roomType))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        stay_period_box.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        jLabel12.setText("Stay Period");

        stayPeriodRange.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stayPeriodRange.setText("Oct 12 2026 - Oct 14 2026");

        jLabel14.setText("Duration");

        duration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duration.setText("3 Nights");

        javax.swing.GroupLayout stay_period_boxLayout = new javax.swing.GroupLayout(stay_period_box);
        stay_period_box.setLayout(stay_period_boxLayout);
        stay_period_boxLayout.setHorizontalGroup(
            stay_period_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stay_period_boxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stay_period_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stay_period_boxLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(stay_period_boxLayout.createSequentialGroup()
                        .addComponent(stayPeriodRange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(duration)))
                .addContainerGap())
        );
        stay_period_boxLayout.setVerticalGroup(
            stay_period_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stay_period_boxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stay_period_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(stay_period_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stayPeriodRange)
                    .addComponent(duration))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("RESERVATION SUMMARY");

        guest_name_box.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 76, 76), 1, true));

        jLabel3.setText("Guest Name");

        guestFullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        guestFullName.setText("Alexander Sterling");

        javax.swing.GroupLayout guest_name_boxLayout = new javax.swing.GroupLayout(guest_name_box);
        guest_name_box.setLayout(guest_name_boxLayout);
        guest_name_boxLayout.setHorizontalGroup(
            guest_name_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guest_name_boxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guest_name_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(guestFullName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        guest_name_boxLayout.setVerticalGroup(
            guest_name_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guest_name_boxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(guestFullName)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CANCELLATION DETAILS");

        jLabel9.setText("Cancellation Reason");

        cancellationReason_1.setText("Guest Request");

        cancellationReason_2.setText("No Show");

        cancellationReason_3.setText("Adminstrative");

        cancellationReason_4.setText("Other");

        jLabel10.setText("Cancellation Notes");

        cancellationNotes.setColumns(20);
        cancellationNotes.setRows(5);
        jScrollPane1.setViewportView(cancellationNotes);

        confirmCancellationBtn.setText("Confirm Cancellation");
        confirmCancellationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmCancellationBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cancellationReason_4)
                        .addGap(18, 18, 18)
                        .addComponent(cancellationReason_4_description))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(cancellationReason_1)
                            .addComponent(cancellationReason_2)
                            .addComponent(cancellationReason_3)
                            .addComponent(jLabel10))
                        .addGap(116, 133, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmCancellationBtn))
                    .addComponent(stay_period_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guest_name_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(room_no_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(room_no_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guest_name_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(stay_period_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancellationReason_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancellationReason_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancellationReason_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancellationReason_4)
                    .addComponent(cancellationReason_4_description, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmCancellationBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void confirmCancellationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmCancellationBtnActionPerformed
        if (reservation == null) return;

        if (!cancellationReason_1.isSelected() && !cancellationReason_2.isSelected()
            && !cancellationReason_3.isSelected() && !cancellationReason_4.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select at least one cancellation reason.",
                "Reason Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cancellationReason_4.isSelected() && cancellationReason_4_description.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please describe the other cancellation reason.",
                "Reason Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        StringBuilder reasons = new StringBuilder("Cancelled - ");
        if (cancellationReason_1.isSelected()) reasons.append("Guest Request, ");
        if (cancellationReason_2.isSelected()) reasons.append("No Show, ");
        if (cancellationReason_3.isSelected()) reasons.append("Administrative, ");
        if (cancellationReason_4.isSelected()) {
            reasons.append("Other: ").append(cancellationReason_4_description.getText().trim()).append(", ");
        }
        if (reasons.length() > 12) reasons.setLength(reasons.length() - 2);
        String cancelNotes = cancellationNotes.getText().trim();
        String combined = reasons.toString();
        if (!cancelNotes.isEmpty()) combined += "\nNotes: " + cancelNotes;

        try {
            reservationController.cancelReservation(reservation.getReservationId(), combined);
            JOptionPane.showMessageDialog(this, "Reservation cancelled successfully.");
            dispose();
        } catch (ValidationException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmCancellationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CancellationDialog dialog = new CancellationDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea cancellationNotes;
    private javax.swing.JCheckBox cancellationReason_1;
    private javax.swing.JCheckBox cancellationReason_2;
    private javax.swing.JCheckBox cancellationReason_3;
    private javax.swing.JCheckBox cancellationReason_4;
    private javax.swing.JTextField cancellationReason_4_description;
    private javax.swing.JButton confirmCancellationBtn;
    private javax.swing.JLabel duration;
    private javax.swing.JLabel guestFullName;
    private javax.swing.JPanel guest_name_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel roomNumber;
    private javax.swing.JLabel roomType;
    private javax.swing.JPanel room_no_box;
    private javax.swing.JLabel stayPeriodRange;
    private javax.swing.JPanel stay_period_box;
    // End of variables declaration//GEN-END:variables
}
