/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms.view;

import hms.config.Constants;
import hms.view.panels.BillingManagementPanel;
import hms.view.panels.DashboardPanel;
import hms.view.panels.GuestManagementPanel;
import hms.view.panels.ReportsPanel;
import hms.view.panels.ReservationPanel;
import hms.view.panels.RoomAssignmentPanel;
import hms.view.panels.RoomManagementPanel;
import hms.view.panels.ServicePanel;
import hms.view.panels.StaffPanel;
import javax.swing.JFrame;

/**
 *
 * @author vickrant-dev
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form dash
     */
    public MainWindow() {
        initComponents();
        
        // Custom Design
        setTitle(Constants.APP_TITLE);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(Constants.WINDOW_WIDTH, Constants.WINDOW_HEIGHT);
        setLocationRelativeTo(null);
        
        setupTabs();
        setAppIcon();
    }

    private void setAppIcon() {
        java.net.URL url = getClass().getResource("/hms/resources/icons/app.png");
        if (url != null) {
            setIconImage(new javax.swing.ImageIcon(url).getImage());
        }
    }
    
    private void setupTabs() {
        main_tab.removeAll();
        main_tab.addTab("Dashboard", new DashboardPanel());
        main_tab.addTab("Guests", new GuestManagementPanel());
        main_tab.addTab("Rooms", new RoomManagementPanel());
        main_tab.addTab("Reservations", new ReservationPanel());
        main_tab.addTab("Billing", new BillingManagementPanel());
        main_tab.addTab("Services", new ServicePanel());
        main_tab.addTab("Staff", new StaffPanel());
        main_tab.addTab("Room Assignments", new RoomAssignmentPanel());
        main_tab.addTab("Reports", new ReportsPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_scroll_pane = new javax.swing.JScrollPane();
        main_panel = new javax.swing.JPanel();
        main_tab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        menu_bar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(1024, 720));

        main_scroll_pane.setBorder(null);
        main_scroll_pane.setViewportView(main_panel);

        main_panel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );

        main_tab.addTab("tab1", jPanel2);

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_tab)
                .addContainerGap())
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_tab)
                .addContainerGap())
        );

        main_scroll_pane.setViewportView(main_panel);

        jMenu1.setText("File");
        menu_bar.add(jMenu1);

        jMenu2.setText("Edit");
        menu_bar.add(jMenu2);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_scroll_pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_scroll_pane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel main_panel;
    private javax.swing.JScrollPane main_scroll_pane;
    private javax.swing.JTabbedPane main_tab;
    private javax.swing.JMenuBar menu_bar;
    // End of variables declaration//GEN-END:variables
}
